version: '3'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/admin
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: npm run serve

  storefront:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/storefront
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    command: npm run serve